### ISSUE TITLE
Can't choose one mention twice

### ISSUE THREAD

**Issue by biggieman** [angular-ui/ui-mention#31]
Can't choose one mention twice.

![ui-mention](https://cloud.githubusercontent.com/assets/16258536/17886045/ba2922e4-6928-11e6-9128-e8a4dd315575.png)

[JSFiddle](https://jsfiddle.net/biggieman/6j5v5856/5/)

**Comment by ProLoser** [comment]
This was something I was aware of when I built the plugin. I believe you can't mention people twice on  Facebook either which is what this is modeled after.  I think I had run into a recursion problem when I tried to do it. 

However the fact that you are able to mention the guy twice probably means we should strip out of the dropdown people who have already been mentioned.

**Comment by biggieman** [comment]
On Facebook I can mention people twice. 
I'll try to think about this issue.

**Comment by mikedon** [comment]
here's a PR that allows duplicates: https://github.com/angular-ui/ui-mention/pull/54

**Comment by biggieman** [comment]
PR #56
