### ISSUE TITLE
How to render stored value in an edit field

### ISSUE THREAD

**Issue by peacepostman** [angular-ui/ui-mention#32]
Hello,

I would like to know if it is possible or if you have any advice, to render the field with several mentions and text if a user want to edit a textarea.

Thanks,

**Comment by ProLoser** [comment]
Can you make a textarea background invisible?

**Comment by peacepostman** [comment]
I am in the exact configuration as in the demo. So i guess yes :)

**Comment by peacepostman** [comment]
OKay i was able to figure out how to do it :)

For those who are seeking how to : 

```
if(attr.data){
          scope.$watch('data', function(newValue) {
            if(newValue){
              // Here i rebuild object to match pattern but if pattern is the same, keep your passed object
              //
              var object = [];
              angular.forEach(scope.data, function(value) {
                var item = {
                  'label' : value.nickname,
                  'picture' : value.picture_url,
                  'id' : value.id
                };
                this.push(item);
              }, object);
              uiMention.mentions = object;
              uiMention.render(scope.raw);
            }
          }, true);
}

```

My **scope.raw** is the message with @[etc..] in it, i pass this as an argument to uiMention.render() in order to render it with correct value after storing them in **uiMention.mentions**

@ProLoser I think you can close my issue, thanks again
