### ISSUE TITLE
Mainters

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/ui-mention#34]
Looking for maintainers (obviously).

Looking at the fork graph, it looks like @JacobMarshallPP is very active. Do you have any interest?

At this time, the only immediate concerns I have are https://github.com/angular-ui/ui-mention/issues/24 and adding @biggieman's tweak here: https://github.com/biggieman/ui-mention/commit/01070547ef74a216b782e027b4930a3a218c2263

**Comment by JacobMarshallPP** [comment]
Sorry @ProLoser, not sure that I really have the time at the moment 😕

I'm definitely interested, but I am afraid there's not enough hours in a day right now. I will keep it in mind though, in case I get freed up.

**Comment by biggieman** [comment]
@ProLoser I made a Pull Request #35 for issue #24

**Comment by biggieman** [comment]
@ProLoser can you give access to npm publish?

**Comment by ProLoser** [comment]
@biggieman Is your npm handle biggieman?

**Comment by biggieman** [comment]
@ProLoser  Yes, all done, thanks!
