### ISSUE TITLE
App crashes after entering invalid string

### ISSUE THREAD

**Issue by Jexordexan** [angular-ui/ui-mention#40]
![screen shot 2016-12-09 at 11 37 52 am](https://cloud.githubusercontent.com/assets/7380810/21056582/38dccf3e-be04-11e6-85f5-2cf1297cc639.png)

Everything works great until you enter a bad mention 😞 

Steps:
- Go to the example page and type in `@xxx` or some other string that has no valid choices. 
- Press enter to select. 

Result:
- A new-line is created
- A `null` is saved as a "mention" 
- The module stops working. 
- Every keystroke produces the following error:
> angular.js:11655 TypeError: Cannot read property 'first' of undefined

Expected: 
- The module continues to work and `@xxx` is rendered as normal text with no new-line.

It seems there are several areas that need null checks for invalid entries.

**Comment by biggieman** [comment]
@ProLoser i think, there is only one place to fix needed.

**Comment by timobehrens** [comment]
+1

**Comment by adampopkiewicz** [comment]
+1

**Comment by ProLoser** [comment]
I am no longer active on this repo. @biggieman I added you as a collaborator so that you can resolve your outstanding PRs, although I would recommend considering my note on #41

**Comment by ProLoser** [comment]
If it wasn't for bower, I'd get rid of the minified files completely.

**Comment by ohadsas** [comment]
+1

**Comment by ProLoser** [comment]
Please use reactions to +1 the original post instead of adding new comments

**Comment by biggieman** [comment]
@ProLoser ok!

**Comment by timobehrens** [comment]
Thanks for fixing this so quickly @biggieman! Could you push a new version to bower please? That would be great!

**Comment by biggieman** [comment]
New release with last fixes will be soon.

**Comment by Jexordexan** [comment]
Bump on the release please! I currently have my bower referencing your commit hash haha

**Comment by biggieman** [comment]
It's released! v0.0.8
