### ISSUE TITLE
Render mentions after save

### ISSUE THREAD

**Issue by georgeportillo** [angular-ui/ui-mention#47]
Hey!

I'm saving the mentions on a server somewhere, and I'd like to render the mentions (with the highlight style and all) -- how would I go about that? Is there a method I can use to trigger that ability?

Thank you!

**Comment by georgeportillo** [comment]
For more context, here's what I'd like to know how to do...

From this:
<img width="328" alt="screen shot 2017-08-03 at 9 32 47 am" src="https://user-images.githubusercontent.com/1437282/28932570-d04ada0c-782e-11e7-993e-80ff6e3feb99.png">

To this:
<img width="331" alt="screen shot 2017-08-03 at 9 33 51 am" src="https://user-images.githubusercontent.com/1437282/28932586-e5b770a8-782e-11e7-93a0-d9170c0f855a.png">

**Comment by biggieman** [comment]
Now all methods are designed to work with editing comments, not with the output of the list of comments. 
1)

**Comment by biggieman** [comment]
Now all methods are designed to work with editing comments, not with the output of the list of comments.

If you have saved both the comment text and metions list, you can do something like this:

```
<div class="comment-body" ng-bind-html="::comment.message | mentionReplace:comment.meta.mention"></div>
```

```
app.filter('mentionReplace', ['$state', function ($state) {
	return function (input, mentions) {
		if (!mentions || !mentions.length) {
			return input;
		}

		var matches = input.match(/@\[.*?\]/g);
		matches = _.uniq(matches);

		var users = {};
		_.forEach(mentions, function (mention) {
			users[mention.id] = mention;
		});

		_.forEach(matches, function (match) {
			var matchTmp = match.substr(2, match.length - 3).split(':');

			if (matchTmp[0] && matchTmp[1] && users[matchTmp[1]]) {
				var user = users[matchTmp[1]];

				input = input.replace(match, '<a href="' + $state.href('app.user', {id: user.id}) + '" class="mention">@' + user.name + '</a>');
			}
		});

		return input;
	};
}]);
```
