### ISSUE TITLE
Support for Angular4/5

### ISSUE THREAD

**Issue by AshishTiwariMEAN** [angular-ui/ui-mention#50]
Is there any way to integrate this plugin  in Angular 4/5. Actually we need to integrate this plugin in updated version for Angular.

**Comment by biggieman** [comment]
Duplicate of #49

**Comment by biggieman** [comment]
Duplicate of #48

**Comment by AshishTiwariMEAN** [comment]
Yes, is there any way to do this ?

**Comment by biggieman** [comment]
Sorry, i can't help you, because i don't work with Angular 2+.

if I have time, I will make a plugin for the Angular 2+

**Comment by AshishTiwariMEAN** [comment]
Ok, Thank you...
