### ISSUE TITLE
Hide dropdown on blur

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/ui-mention#6]
Running into annoying circles trying to not remove the dropdown BEFORE the `ng-click` fires.

**Comment by kasperlewau** [comment]
Forgive my (potential) stupidity here but - I don't see the issue when running the example code locally. 
Dropping focus off of the input with a `@k` (dropdown visible), will kill the dropdown. 

The example code at `gh-pages` seems to be outdated however. 

Did #7 close this one off, or am I misinterpreting the issue?

**Comment by ProLoser** [comment]
Hmm I think you might be right
