### ISSUE TITLE
mention cover position issue in textarea with scrollbar

### ISSUE THREAD

**Issue by Astray-git** [angular-ui/ui-mention#8]
If I have more lines than textarea row, the mention cover always stays at the same position
![mention1](https://cloud.githubusercontent.com/assets/2520426/9055288/15dfac12-3abc-11e5-869d-a6479ed36a02.png)
scroll
![mention2](https://cloud.githubusercontent.com/assets/2520426/9055287/15db997e-3abc-11e5-82f5-030aa1b13756.png)

**Comment by ProLoser** [comment]
This is why auto grow behavior is mandatory. For now, what happens if you
set the textarea to box-sizing:border-box;

**Comment by Astray-git** [comment]
Thanks for the prompt response.
With box-sizing:border-box; height of the textarea will auto grow. Hmm now it's the same behavior as Facebook's input box.
So for now I can't give a max-height to textarea?

**Comment by ProLoser** [comment]
Not at this time. It would require having the textarea and rendering div
scroll in sync which although is not impossible, adds complexity I'm not
concerned with at this time. You are free to explore developing an
enhancement for such functionality but even facebook doesn't.
